// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJw-FJo0l6MIkwZCqjHFAldIIeU4b-E4o',
    appId: '1:595810269406:web:27e83fd6e11132f91f2a4f',
    messagingSenderId: '595810269406',
    projectId: 'notify-b0f84',
    authDomain: 'notify-b0f84.firebaseapp.com',
    storageBucket: 'notify-b0f84.appspot.com',
    measurementId: 'G-CZNGS6FED2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXecXTTjR9_m2a0IxYPERIPBsD8I6tqF0',
    appId: '1:595810269406:android:6dd1100baab36bdd1f2a4f',
    messagingSenderId: '595810269406',
    projectId: 'notify-b0f84',
    storageBucket: 'notify-b0f84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO8L8E0TOrTqlQkOamiD77slgCYd2T6gg',
    appId: '1:595810269406:ios:4e041050c0700a051f2a4f',
    messagingSenderId: '595810269406',
    projectId: 'notify-b0f84',
    storageBucket: 'notify-b0f84.appspot.com',
    iosBundleId: 'com.example.wsb119Notify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO8L8E0TOrTqlQkOamiD77slgCYd2T6gg',
    appId: '1:595810269406:ios:4e041050c0700a051f2a4f',
    messagingSenderId: '595810269406',
    projectId: 'notify-b0f84',
    storageBucket: 'notify-b0f84.appspot.com',
    iosBundleId: 'com.example.wsb119Notify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJw-FJo0l6MIkwZCqjHFAldIIeU4b-E4o',
    appId: '1:595810269406:web:8dcaa67dad6244881f2a4f',
    messagingSenderId: '595810269406',
    projectId: 'notify-b0f84',
    authDomain: 'notify-b0f84.firebaseapp.com',
    storageBucket: 'notify-b0f84.appspot.com',
    measurementId: 'G-QVD512BXPF',
  );
}
